language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer self-update

before_script:
  - composer update --no-interaction

script:
  - ./vendor/bin/phpunit
